# Generated by Django 4.2 on 2025-05-31 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
    ]
